---
title: "Cleaning"
author: "Paul Geneta"
date: "2024-06-27"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
```

[Kaggle link](https://www.kaggle.com/code/tgomesjuliana/crossfit-games-competition-data-cleaning?scriptVersionId=137772920)

```{r}
#Load libraries
library(tidyr)
library(tidyverse)

#Load Dataset
dataset <- read.csv("~/Documents/R/Crossfit/data/df_games_conso.csv", stringsAsFactors = F)

```



Fix countryofOriginName and regionName
```{r}
# dataset %>% 
#   filter(countryOfOriginCode != "",
#          countryOfOriginName == "") 

canada_regions <- c("Canada East", "Canada West")

US_regions <- c('Northern California', 'Southern California', 'Central East', 'Mid Atlantic','North Central', 'North East', 'North West', 
                'South Central', 'South East', 'South West')

north_america_countries <- c('Canada', 'United States', 'Cayman Islands', 'Jamaica')

central_america_countries <- c('Belize', 'Costa Rica', 'Dominican Republic', 'El Salvador', 'Guatemala', 'Honduras','Mexico', 
                               'Nicaragua', 'Panama')

south_america_countries <- c('Argentina', 'Bahamas', 'Barbados', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Guyana', 
                             'Jamaica', 'Kosovo', 'Morocco', 'Paraguay', 'Peru', 'Saint Lucia', 'Suriname','Trinidad and Tobago', 
                             'Uruguay', 'Venezuela')

europe_countries <- c('Andorra', 'Austria', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus',
                    'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Iceland', 
                    'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Norway', 'Poland',
                    'Portugal', 'Romania', 'Russia', 'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland',
                    'Turkey', 'Ukraine', 'United Kingdom')

african_countries <- c('Algeria', 'Angola', 'Botswana', 'Egypt', 'Ghana', 'Kenya', 'Mauritius', 'Mozambique', 'Namibia',
                    'Nigeria', 'Senegal', 'South Africa', 'Tunisia', 'Zimbabwe')

asian_countries <-  c('Afghanistan', 'Bahrain', 'Brunei Darussalam', 'Cambodia', 'China', 'Egypt', 'India', 'Indonesia',
                  'Iran', 'Iraq', 'Israel', 'Japan', 'Jordan', 'Korea, Republic of', 'Kuwait', 'Lebanon', 'Malaysia', 
                  'Oman', 'Pakistan', 'Palestinian Territory', 'Philippines', 'Qatar', 'Saudi Arabia', 'Singapore', 
                  'Sri Lanka', 'Syrian Arab Republic', 'Turkey', 'United Arab Emirates', 'Viet Nam', 'Russian Federation',
                  'United Arab Emirates')

oceania_countries <- c('Australia', 'New Zealand', 'Papua New Guinea', 'Samoa', 'Tonga')

df_clean <- dataset %>% 
  mutate(
    countryOfOriginName = case_when( #fix specific countryofOriginCode values with corresponding countryofOriginName
    countryOfOriginCode == "BY" ~ "Belarus",
    countryOfOriginCode == "RU" ~ "Russian Federation",
    regionName %in% canada_regions ~ "Canada",
    regionName %in% US_regions ~ "United States",
    TRUE ~ countryOfOriginName),
    regionName = case_when( #fix specific regionName values with corresponding countryofOriginName
    countryOfOriginName %in% north_america_countries ~ "North America",
    countryOfOriginName %in% central_america_countries ~ "Central America",
    countryOfOriginName %in% south_america_countries ~ "South America",
    countryOfOriginName %in% europe_countries ~ "Europe",
    countryOfOriginName %in% african_countries ~ "Africa",
    countryOfOriginName %in% asian_countries ~ "Asia",
    countryOfOriginName %in% oceania_countries ~ "Oceania",
    regionName == "Latin America" ~ "South America",
    regionName == "Australia" ~ "Oceania",
    TRUE ~ regionName
    )
  )



```


```{r}
#count the number of unique regionName values for each countryofOriginName
df_clean %>% 
  group_by(countryOfOriginName) %>% 
  summarise(regionName_unique = n_distinct(regionName)) %>% 
  filter(regionName_unique >= 2)

```


```{r}
# Filter 'countryOfOriginName' not null while 'regionName' is null (expected to be empty)
df_clean %>% 
  filter(countryOfOriginName != "",
         regionName == "")
```


```{r}
# Filter 'regionName' not null while 'CountryofOriginName' is null 
df_clean %>% 
  filter(countryOfOriginName == "",
         regionName != "")
```


```{r}
#Filter unique countryofOriginName
unique(df_clean$countryOfOriginName)
```


```{r}
#Unique region names
unique(df_clean$regionName)
```


Fix countryofOriginCode and regionId plus add statusId

```{r}
df_clean2 <- df_clean %>% 
  mutate(countryOfOriginCode = ifelse(countryOfOriginCode == "", 0, countryOfOriginCode),
         countryOfOriginName = ifelse(countryOfOriginName == "", 0, countryOfOriginName),
         regionName = ifelse(regionName == "", 0, regionName),
         region_id_map = case_when(
           regionName %in% north_america_countries ~ "1",
           regionName %in% central_america_countries ~ "2",
           regionName %in% south_america_countries ~ "3",
           regionName %in% europe_countries ~ "4",
           regionName %in% african_countries ~ "5",
           regionName %in% asian_countries ~ "6",
           regionName %in% oceania_countries ~ "7",
           TRUE ~ regionName
         ),
         regionId = region_id_map)


head(df_clean2)
```


```{r}
# Filter 'countryOfOriginName' not null while 'regionName' is null (expected to be empty)
head(df_clean2 %>% 
  filter(countryOfOriginName != "",
         regionName == ""))
```


```{r}
# Filter 'regionName' not null while 'CountryofOriginName' is null 
head(df_clean2 %>% 
  filter(countryOfOriginName == "",
         regionName != ""))
```


Fix height and weight and add BMI

```{r}
df_clean3<- df_clean2 %>% 
  separate(height, c("height", "height_metric")) %>%  #Separate column
  separate(weight, c("weight", "weight_metric")) %>%  
  mutate(height = as.numeric(height), #convert to numeric
         weight = as.numeric(weight),
         height_cm = if_else(height_metric == "in", height*2.54, height), #do calculations to convert to kg, and cm
         weight_kg = if_else(weight_metric == "lb", weight/2.20462, height),
         BMI = (weight_kg / (height_cm^2))*10000) %>% #bmi calculation
  select(-height_metric, -weight_metric, -height, -weight) #clean up full df

head(df_clean3)
```

Sort overall score

```{r}
# Replace DQ with -1, indicating competitor was disqualified
#Convert overallRank as numeric
df_clean4 <- df_clean3 %>% 
  mutate(overallRank = ifelse(overallRank == "DQ", -1, overallRank),
         overallRank = as.numeric(overallRank))

#See which competitors have a 0 placing
df_clean4 %>% 
  filter(overallRank == 0)

#Define dictionary conditions to map specific competitorId and year to their corresponding overallRank values
conditions <- c(
  `455677_2021` = 38,
  `592472_2021` = 39,
  `1019212_2021` = 40,
  `901702_2021` = 39,
  `975774_2021` = 40,
  `975774_2018` = 40,
  `3200_2015` = 40,
  `14354_2014` = 40,
  `151906_2013` = 47
)

#function to get the key for the conditions vector
get_condition_key <-  function(competitorId, year){
  paste0(competitorId, year, sep = "_")
}

#Apply the conditions mapping to overallRank based on the competitorId and year conditions
df_clean5 <- df_clean4 %>% 
  mutate(overallRank = ifelse(
    get_condition_key(competitorId, year) %in% names(conditions),
    conditiona[get_condition_key(competitorId, year)],
    overallRank
  ))


df_clean5 %>% 
  filter(overallScore == grepl(':', overallScore))

#replace ":" with empty string and divide by 100, only for rows where : is present
df_clean6 <- df_clean5 %>% 
  mutate(overallScore = suppressWarnings(if_else(
    grepl(':', overallScore),
    as.numeric(gsub(':', '', overallScore))/100,
    as.numeric(overallScore)))
    )
```




```{r}
#Create null dummy columns for height, weight, age and BMI
df_clean7 <- df_clean6 %>% 
  replace_na(list(height_cm = 0, weight_kg = 0, age = 0, BMI = 0)) %>% 
  mutate(height_null = if_else(height_cm == 0, 1, 0),
         weight_null = if_else(weight_kg == 0, 1, 0),
         age_null = if_else(age == 0, 1, 0),
         bmi_null = if_else(BMI == 0, 1, 0))

#calculate average height, weight and bmi by gender
# avg_stats <- df_clean7 %>% 
#   filter(BMI < 100) %>% #filtering out extremes - unable to find real height and weight for athletes online
#   group_by(gender) %>% 
#   summarise(mean_height = mean(height_cm, na.rm = T),
#             mean_weight = mean(weight_kg, na.rm = T),
#             mean_bmi = mean(BMI, na.rm = T))
# 
# avg_stats
#Apply avg stats to those with 1 on dummy variables

get_stat <- function(data, stat = c('height', 'weight', 'bmi')){
  
  if(stat == 'height'){
  
  height <- data %>% 
  #filter(gender == gen) %>% 
  group_by(gender) %>% 
  summarise(height = mean(height_cm, na.rm=T)) %>% 
  pull(height)
  
  return(height)

}else if(stat == 'weight'){
  
  weight <- data %>% 
  #filter(gender == gen) %>% 
  group_by(gender) %>% 
  summarise(weight = mean(weight_kg, na.rm=T)) %>% 
  pull(weight)
  
  return(weight)
}
  else{
    bmi <- data %>% 
  #filter(gender == gen) %>% 
  group_by(gender) %>% 
  summarise(bmi = mean(BMI, na.rm=T)) %>% 
  pull(bmi)
    
    return(bmi)
  }


}

get_stat(df_clean7 %>% filter(gender == "M"), 'height')
# get_stat(df_clean7 %>% filter(gender == "F"), 'height')
# heightM <- get_stat(df_clean7 %>% filter(gender == "M"), 'height')
# bmiF <- get_stat(df_clean7 %>%  filter(gender == "M"), 'bmi')
# weight




df_clean8F <- df_clean7 %>% 
  filter(gender == "F") %>% 
  mutate(height_cm = if_else(height_null == 1, get_stat(df_clean7 %>% filter(gender == 'F'), 'height'), height_cm),
         weight_kg = if_else(weight_null == 1, get_stat(df_clean7 %>% filter(gender == 'F'), 'weight'), weight_kg),
         BMI = if_else(bmi_null == 1, get_stat(df_clean7 %>% filter(gender == 'F'), 'bmi'), BMI))

df_clean8M <- df_clean7 %>% 
  filter(gender == "M") %>% 
  mutate(height_cm = if_else(height_null == 1, get_stat(df_clean7 %>% filter(gender == 'M'), 'height'), height_cm),
         weight_kg = if_else(weight_null == 1, get_stat(df_clean7 %>% filter(gender == 'M'), 'weight'), weight_kg),
         BMI = if_else(bmi_null == 1, get_stat(df_clean7 %>% filter(gender == 'M'), 'bmi'), BMI))

#Join dataset back together and Fill null values in affiliateID with 0 and convert affiliateID to integer
df_clean9 <- rbind(df_clean8F, df_clean8M) %>% 
  mutate(affiliateId = ifelse(affiliateId == "None", 0, affiliateId)) %>% 
  arrange(competitorId, year)


```





```{r}
#add games competition

```



































